export const T = {
  bg: "#F2EDE6",
  surface: "#FFFFFF",
  sidebar: "#14100E",
  sidebarActive: "#A6634B",
  border: "#DDD5CB",
  borderDark: "#C4B8AB",
  gold: "#A6634B",
  goldLight: "#F5EBE3",
  goldDark: "#7D4F3C",
  sage: "#5C6B62",
  sageLight: "#E8ECE9",
  rose: "#C0544A",
  roseLight: "#FDF0EE",
  green: "#4A8C6A",
  greenLight: "#EBF5EF",
  amber: "#B87333",
  amberLight: "#FBF3EA",
  text: "#14100E",
  textMid: "#5C4F3F",
  textMuted: "#9C8C7C",
  white: "#FFFFFF",
  charcoal: "#2A221C",
};

export const chartTooltip = {
  contentStyle: {
    background: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: 10,
    fontSize: 12,
    color: T.text,
    boxShadow: "0 4px 20px rgba(0,0,0,0.07)",
  },
  cursor: false,
};
